---
apiVersion: v1
kind: Secret
metadata:
  name: ${ROLE}-cluster-${PROVIDER}
  labels:
    argocd.argoproj.io/secret-type: cluster
    clusterType: ${ROLE}
    location: ${LOCATION}
    provider: ${PROVIDER}
type: Opaque
stringData:
  name: ${ROLE}-cluster
  server: https://kubernetes.default.svc
  config: |
    {
      "tlsClientConfig": {
        "insecure":false
      }
    }
