---
# Deploy base line config and dependencies
##########################################
- hosts: hetzner_hcloud
  gather_facts: yes
  become: yes
  roles:
    - role: ../../roles/base/hetzner/host/hcloud

- hosts: hetzner_bare_metal
  gather_facts: yes
  become: yes
  roles:
    - role: ../../roles/base/hetzner/host/metal

- hosts: k3s_cluster_compute
  become: yes
  gather_facts: yes
  roles:
    - role: ../../roles/hvswitch

- name: Build a cluster with HA control plane
  hosts: k3s_cluster
  roles:
    - role: xanmanning.k3s

- hosts: k3s_cluster_master
  become: yes
  gather_facts: yes
  roles:
    - role: ../../roles/k3s

- name: Prepare GitHub Actions Runner
  hosts: k3s_cluster_compute
  become: yes
  gather_facts: yes
  roles:
    - role: ../../roles/github_runner

- name: Install GitHub Actions Runner
  hosts: k3s_cluster_compute
  become: yes
  vars:
    - github_account: tantlinger
    - runner_org: yes
    - runner_user: github
    - runner_labels: ['hetzner']
    - access_token: "{{ lookup('env', 'PERSONAL_ACCESS_TOKEN') }}"
  roles:
    - role: monolithprojects.github_actions_runner
