---
# Install kubernetes
- name: Build a cluster with HA control plane
  hosts: k3s_cluster
  roles:
    - role: xanmanning.k3s

- hosts: k3s_cluster_master
  become: yes
  gather_facts: yes
  roles:
    - role: ../../roles/k3s

- hosts: k3s_cluster_master
  become: yes
  gather_facts: yes
  roles:
    - role: ../../roles/base/novoserve/mgmnt/metal

- name: Prepare GitHub Actions Runner
  hosts: k3s_cluster_master
  become: yes
  gather_facts: yes
  roles:
    - role: ../../roles/github_runner

- name: Install GitHub Actions Runner
  hosts: k3s_cluster_master
  become: yes
  vars:
    - github_account: tantlinger
    - runner_org: yes
    - runner_user: github
    - runner_labels: ['novoserve']
    - access_token: "{{ lookup('env', 'PERSONAL_ACCESS_TOKEN') }}"
  roles:
    - role: monolithprojects.github_actions_runner
