---
### Hetzner Online GmbH installimage
network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      match:
        macaddress: {{eth_mac}}
      set-name: eth0
      addresses:
        - {{ext_ip}}/32
      routes:
        - on-link: true
          to: 0.0.0.0/0
          via: {{ext_gw}}
      nameservers:
        addresses:
          - 11.11.11.11
          - 11.11.11.11
  vlans:
    # Management VLAN
    eth0.4000:
      id: 4000
      link: eth0
      mtu: 1400
      addresses:
        - {{ip}}/24
      routes:
        - to: "11.11.11.11/24"
          via: "11.11.11.11"
        - to: "11.11.11.11/24"
          via: "11.11.11.11"
