---
# Deploy base line config and dependencies
##########################################
- hosts: hetzner_bare_metal
  gather_facts: yes
  become: yes
  roles:
    - role: ../../roles/base

- hosts: k3s_cluster_compute
  become: yes
  gather_facts: yes
  roles:
    - role: ../../roles/hvswitch

- name: Build a cluster with HA control plane
  hosts: k3s_cluster
  roles:
    - role: xanmanning.k3s

- hosts: k3s_cluster_master
  become: yes
  gather_facts: yes
  roles:
    - role: ../../roles/k3s
