---
# Install kubernetes
- name: Build a cluster with HA control plane
  hosts: k3s_cluster
  roles:
    - role: xanmanning.k3s

- hosts: k3s_cluster_master
  become: yes
  gather_facts: yes
  roles:
    - role: ../../roles/k3s
